#!/bin/bash

function showtime()
{
    tput clear
    now=$(date +"%I:%M %P") # show HH:MM: PP
    second=$(date +"%S")
    toilet -f 3d.flf $now | lolcat
    sleep $((60-$second))
    showtime
}

# check figlet font file
fontpath=/usr/share/figlet
font=$fontpath/3d.flf
if [[ ! -f $font ]]; then
    cd $fontpath
    echo Installing font file to $fontpath
    wget https://raw.githubusercontent.com/xero/figlet-fonts/master/3d.flf
fi


gnome-terminal --title="lolclock" --geometry 55x10 -- bash -c "$(declare -f showtime); showtime; bash" &
