#!/bin/bash

function showtime()
{
    tput clear
    now=$(date +"%I:%M %P") # show HH:MM: PP
    second=$(date +"%S")
    toilet -f 3d.flf $now | lolcat
    sleep $((60-$second))
    showtime
}

# check figlet font file
fontpath=/usr/share/figlet
font=$fontpath/3d.flf
if [[ ! -f $font ]]; then
    cd $fontpath
    echo Installing font file to $fontpath
    wget https://raw.githubusercontent.com/xero/figlet-fonts/master/3d.flf
fi

function help()
{
    echo ""
    echo "lolclock usage: "
    echo "          -h --help    : Check this help message."
    echo "   -g --gnome-terminal : Open new gnome terminal window with lolclock." 
    echo ""
    exit 1
}

case $1 in 
    -g|--gnome-terminal)
        gnome-terminal --title="lolclock" --geometry 55x10 -- bash -c "$(declare -f showtime); showtime; bash" &
	;;
    -h|--help)
        help
	;;
    *)
        tput clear
	showtime
	;;
esac
